### ISSUE TITLE
this does not work

### ISSUE THREAD

**Issue by niftylettuce** [koa-modules/serve-static#2]

**Comment by haoxins** [comment]
@niftylettuce what's you koa's version and this module's version

**Comment by haoxins** [comment]
reopen if there are more details >_<

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
With koa@2.0.0-alpha.3 (though this doesn't matter) and koa-serve-static@2d017cc51e7e6d873024e63be0fbbe01070bce9d

If `serve-static` passes through (calls its next), the promise is rejected, without `koa-serve-static` calling its next.
