### ISSUE TITLE
Undefined exception thrown 

### ISSUE THREAD

**Issue by gx0r** [koa-modules/serve-static#3]
I am getting an undefined exception from this mdidleware. I became aware of it is from using:

https://github.com/llambda/koa-boiler/blob/master/app.js#L46

This type of error handler would receive an undefined value when a browser hits a page that doesn't exist. The undefined exception is thrown and the browser never receives a 404 response.

I'll try to come up with more detail / test case as this description may not be enough.

**Comment by fundon** [comment]
Good catch!

**Comment by fundon** [comment]
@llambda 

Maybe below case can help you.

``` js
  return serveStatic(`${__dirname}/public`)(ctx).catch((err) => {
    ctx.res.statusCode = err ? (err.status || 502) : 404
    ctx.res.end(err ? err.stack : 'Not Found!')
  })
```
